mongo:
  uri: mongodb://localhost:27017/blog

#spring:
#  datasource:
#    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
#    username: test
#    password: test
#    driver-class-name: org.h2.Driver
#debug: true